{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-helmchart-virtualservice
  labels:
    app: my-helmchart-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - my-helmchart-gateway
  http:
    - match:
        - uri:
            prefix: {{ .Values.istio.prefixPath }}
      rewrite:
        uri: /
      route:
        - destination:
            host: my-helmchart-spring
            port:
              number: {{ .Values.service.port }}
{{- end }}