apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-helmchart-spring
  labels:
    app: my-helmchart-spring
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-helmchart-spring
  template:
    metadata:
      labels:
        app: my-helmchart-spring
    spec:
      containers:
        - name: spring-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}