apiVersion: v1
kind: Service
metadata:
  name: my-helmchart-spring
  labels:
    app: my-helmchart-spring
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-helmchart-spring
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP