replicaCount: 3

image:
  repository: ghcr.io/biasmj016/my-helmchart
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Istio 설정
istio:
  enabled: true
  gatewayPort: 80
  prefixPath: /sample

# Grafana 설정
grafana:
  enabled: true
  replicaCount: 1
  adminPassword: "admin"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"